//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XColumn.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XColumn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ユーザー追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChromeImport_Cancel {
            get {
                return ResourceManager.GetString("ChromeImport_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PC内のChromeブラウザから検出された拡張機能一覧です。
        ///インポートしたい項目にチェックを入れてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChromeImport_Description {
            get {
                return ResourceManager.GetString("ChromeImport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポート中にエラーが発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChromeImport_Error {
            get {
                return ResourceManager.GetString("ChromeImport_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡張機能名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChromeImport_ExtensionName {
            get {
                return ResourceManager.GetString("ChromeImport_ExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択した項目をインポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChromeImport_Import {
            get {
                return ResourceManager.GetString("ChromeImport_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chromeのデフォルトプロファイルから拡張機能が見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChromeImport_NoExtensionsFound {
            get {
                return ResourceManager.GetString("ChromeImport_NoExtensionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポートする拡張機能を選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChromeImport_NoExtensionsSelected {
            get {
                return ResourceManager.GetString("ChromeImport_NoExtensionsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChromeImport_Select {
            get {
                return ResourceManager.GetString("ChromeImport_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chromeから拡張機能をインポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChromeImport_Title {
            get {
                return ResourceManager.GetString("ChromeImport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Complete {
            get {
                return ResourceManager.GetString("Common_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択した項目を削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_DeleteSelected {
            get {
                return ResourceManager.GetString("Common_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」をNGワードに追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ctx_AddNgWord {
            get {
                return ResourceManager.GetString("Ctx_AddNgWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ctx_Copy {
            get {
                return ResourceManager.GetString("Ctx_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンクのアドレスをコピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ctx_CopyLinkAddress {
            get {
                return ResourceManager.GetString("Ctx_CopyLinkAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り取り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ctx_Cut {
            get {
                return ResourceManager.GetString("Ctx_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このカラムを削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ctx_DeleteColumn {
            get {
                return ResourceManager.GetString("Ctx_DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Googleで「{0}」を検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ctx_GoogleSearch {
            get {
                return ResourceManager.GetString("Ctx_GoogleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ctx_Paste {
            get {
                return ResourceManager.GetString("Ctx_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前を付けて画像を保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ctx_SaveImageAs {
            get {
                return ResourceManager.GetString("Ctx_SaveImageAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバッグ情報の保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DebugInfo_SaveTitle {
            get {
                return ResourceManager.GetString("DebugInfo_SaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   許可されていないドメインです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_DomainNotAllowed {
            get {
                return ResourceManager.GetString("Err_DomainNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期化エラー: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_InitFailed {
            get {
                return ResourceManager.GetString("Err_InitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IDかURLを入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_InputIdOrUrl {
            get {
                return ResourceManager.GetString("Err_InputIdOrUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効な拡張機能のフォルダではありません（manifest.jsonが見つかりません）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_InvalidExtensionFolder {
            get {
                return ResourceManager.GetString("Err_InvalidExtensionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効なURLです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_InvalidUrl {
            get {
                return ResourceManager.GetString("Err_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンクを開けませんでした: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_LinkOpenFailed {
            get {
                return ResourceManager.GetString("Err_LinkOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像の保存に失敗しました。\n{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_SaveImageFailed {
            get {
                return ResourceManager.GetString("Err_SaveImageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_SelectFolder {
            get {
                return ResourceManager.GetString("Err_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイルを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Err_SelectProfileFirst {
            get {
                return ResourceManager.GetString("Err_SelectProfileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダから追加... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extension_AddFromFolder {
            get {
                return ResourceManager.GetString("Extension_AddFromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この拡張機能は既に追加されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extension_AlreadyAdded {
            get {
                return ResourceManager.GetString("Extension_AlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extension_Cancel {
            get {
                return ResourceManager.GetString("Extension_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡張機能 &apos;{0}&apos; を削除しますか？
        ///(インポートされたフォルダも完全に削除されます) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extension_ConfirmRemove {
            get {
                return ResourceManager.GetString("Extension_ConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extension_Enabled {
            get {
                return ResourceManager.GetString("Extension_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダ削除の一部失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extension_FolderDeletePartialFailTitle {
            get {
                return ResourceManager.GetString("Extension_FolderDeletePartialFailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chromeからインポート... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extension_ImportFromChrome {
            get {
                return ResourceManager.GetString("Extension_ImportFromChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択された拡張機能はすでに追加されています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extension_NoNewExtensions {
            get {
                return ResourceManager.GetString("Extension_NoNewExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この拡張機能には設定ページがないか、まだロードされていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extension_NoOptionsPage {
            get {
                return ResourceManager.GetString("Extension_NoOptionsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extension_OK {
            get {
                return ResourceManager.GetString("Extension_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extension_OpenFolder {
            get {
                return ResourceManager.GetString("Extension_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extension_Options {
            get {
                return ResourceManager.GetString("Extension_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extension_Remove {
            get {
                return ResourceManager.GetString("Extension_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chrome拡張機能のフォルダ（manifest.jsonが含まれるフォルダ）を選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Extension_SelectFolderPrompt {
            get {
                return ResourceManager.GetString("Extension_SelectFolderPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡張機能エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExtensionError {
            get {
                return ResourceManager.GetString("ExtensionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡張機能の管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExtensionManagement {
            get {
                return ResourceManager.GetString("ExtensionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Filter_AllFiles {
            get {
                return ResourceManager.GetString("Filter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Filter_ImageFiles {
            get {
                return ResourceManager.GetString("Filter_ImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GitHub に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Input_Cancel {
            get {
                return ResourceManager.GetString("Input_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Input_OK {
            get {
                return ResourceManager.GetString("Input_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Input_Title {
            get {
                return ResourceManager.GetString("Input_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   後で に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グローバルトレンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_AddGlobalTrend {
            get {
                return ResourceManager.GetString("Menu_AddGlobalTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_AddHome {
            get {
                return ResourceManager.GetString("Menu_AddHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リスト... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_AddList {
            get {
                return ResourceManager.GetString("Menu_AddList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リスト(一覧) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_AddListAuto {
            get {
                return ResourceManager.GetString("Menu_AddListAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_AddNotify {
            get {
                return ResourceManager.GetString("Menu_AddNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_AddSearch {
            get {
                return ResourceManager.GetString("Menu_AddSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トレンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_AddTrend {
            get {
                return ResourceManager.GetString("Menu_AddTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_AddUser {
            get {
                return ResourceManager.GetString("Menu_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバッグ情報をエクスポート... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_DebugInfo {
            get {
                return ResourceManager.GetString("Menu_DebugInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡張機能の管理... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Extensions {
            get {
                return ResourceManager.GetString("Menu_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込み中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Loading {
            get {
                return ResourceManager.GetString("Menu_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規カラムを追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_NewColumn {
            get {
                return ResourceManager.GetString("Menu_NewColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   別プロファイルのタイムライン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_OtherProfile {
            get {
                return ResourceManager.GetString("Menu_OtherProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル(_P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Profile {
            get {
                return ResourceManager.GetString("Menu_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Profile_Delete {
            get {
                return ResourceManager.GetString("Menu_Profile_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複製... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Profile_Duplicate {
            get {
                return ResourceManager.GetString("Menu_Profile_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   別窓で起動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Profile_LaunchNew {
            get {
                return ResourceManager.GetString("Menu_Profile_LaunchNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Profile_Manage {
            get {
                return ResourceManager.GetString("Menu_Profile_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規作成... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Profile_New {
            get {
                return ResourceManager.GetString("Menu_Profile_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前変更... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Profile_Rename {
            get {
                return ResourceManager.GetString("Menu_Profile_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このプロファイルに切り替える に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Profile_Switch {
            get {
                return ResourceManager.GetString("Menu_Profile_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクティブ時自動更新停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_StopActiveTimer {
            get {
                return ResourceManager.GetString("Menu_StopActiveTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご支援・寄付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Support {
            get {
                return ResourceManager.GetString("Menu_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツール(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_Cancel {
            get {
                return ResourceManager.GetString("Message_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いいえ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_No {
            get {
                return ResourceManager.GetString("Message_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_OK {
            get {
                return ResourceManager.GetString("Message_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_Yes {
            get {
                return ResourceManager.GetString("Message_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}
        ///
        ///快適なXライフを。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_About_Body {
            get {
                return ResourceManager.GetString("Msg_About_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在使用中のプロファイル「{0}」を完全に複製するには、アプリの再起動が必要です。
        ///
        ///今すぐ再起動して複製を行いますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ConfirmCloneActiveProfile {
            get {
                return ResourceManager.GetString("Msg_ConfirmCloneActiveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡張機能 &apos;{0}&apos; を削除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ConfirmDeleteExtension {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル「{0}」を本当に削除しますか？
        ///設定やカラム情報がすべて失われます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ConfirmDeleteProfile {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイルを「{0}」に切り替えますか？
        ///(アプリが再起動します) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ConfirmProfileSwitch {
            get {
                return ResourceManager.GetString("Msg_ConfirmProfileSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバッグ情報をクリップボードにコピーしました。
        ///サポートに連絡する際に貼り付けてください。
        ///
        ///※この情報には認証トークンなどの機密情報は含まれていませんが、
        ///念のため内容を確認してから送信することをお勧めします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_DebugInfoExported {
            get {
                return ResourceManager.GetString("Msg_DebugInfoExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在使用中のプロファイル「{0}」は削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_CannotDeleteActive {
            get {
                return ResourceManager.GetString("Msg_Err_CannotDeleteActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポート中にエラーが発生しました。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_ChromeImportFailed {
            get {
                return ResourceManager.GetString("Msg_Err_ChromeImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバッグ情報のエクスポートに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_DebugExportFailed {
            get {
                return ResourceManager.GetString("Msg_Err_DebugExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除中にエラーが発生しました。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_DeleteFailed {
            get {
                return ResourceManager.GetString("Msg_Err_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リストからは削除されましたが、フォルダの物理削除に一部失敗しました。
        ///拡張機能がバックグラウンドで使用中の可能性があります。
        ///
        ///アプリを再起動した後、以下のフォルダを手動で削除してください。
        ///
        ///パス: {0}
        ///詳細: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_ExtensionFolderDeleteFailed {
            get {
                return ResourceManager.GetString("Msg_Err_ExtensionFolderDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡張機能 &apos;{0}&apos; の読み込みに失敗しました。
        ///
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_ExtensionLoadFailed {
            get {
                return ResourceManager.GetString("Msg_Err_ExtensionLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたフォルダが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_FolderNotFound {
            get {
                return ResourceManager.GetString("Msg_Err_FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいウィンドウの起動に失敗しました。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_LaunchFailed {
            get {
                return ResourceManager.GetString("Msg_Err_LaunchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダを開けませんでした。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_OpenFolderFailed {
            get {
                return ResourceManager.GetString("Msg_Err_OpenFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ページを開けませんでした。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_OpenPageFailed {
            get {
                return ResourceManager.GetString("Msg_Err_OpenPageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作に失敗しました。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_OperationFailed {
            get {
                return ResourceManager.GetString("Msg_Err_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイルの複製中にエラーが発生しました。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_ProfileCloneFailed {
            get {
                return ResourceManager.GetString("Msg_Err_ProfileCloneFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル「{0}」は既に存在します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_ProfileExists {
            get {
                return ResourceManager.GetString("Msg_Err_ProfileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その名前のプロファイルは既に存在します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_ProfileNameExists {
            get {
                return ResourceManager.GetString("Msg_Err_ProfileNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル名に使用できない文字が含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_ProfileNameInvalid {
            get {
                return ResourceManager.GetString("Msg_Err_ProfileNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前の変更に失敗しました。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_RenameFailed {
            get {
                return ResourceManager.GetString("Msg_Err_RenameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 個の拡張機能をインポートしました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ExtensionsImported {
            get {
                return ResourceManager.GetString("Msg_ExtensionsImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語設定を変更しました。
        ///変更を完全に適用するにはアプリの再起動が必要です。
        ///
        ///今すぐ再起動しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_LanguageChanged_Restart {
            get {
                return ResourceManager.GetString("Msg_LanguageChanged_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」をNGワードに追加しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_NgWordAdded {
            get {
                return ResourceManager.GetString("Msg_NgWordAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他のプロファイルがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_NoOtherProfiles {
            get {
                return ResourceManager.GetString("Msg_NoOtherProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル「{0}」を作成しました。
        ///新しいプロファイルに切り替えますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ProfileCreated {
            get {
                return ResourceManager.GetString("Msg_ProfileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル「{0}」を削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ProfileDeleted {
            get {
                return ResourceManager.GetString("Msg_ProfileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル名を「{0}」に変更しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ProfileRenamed {
            get {
                return ResourceManager.GetString("Msg_ProfileRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定を変更しました。
        ///反映するにはアプリの再起動が必要です。
        ///今すぐ再起動しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_RestartConfirm {
            get {
                return ResourceManager.GetString("Msg_RestartConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※変更を適用するにはアプリの再起動が必要です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_RestartRequired {
            get {
                return ResourceManager.GetString("Msg_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポートする拡張機能を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_SelectImportExtension {
            get {
                return ResourceManager.GetString("Msg_SelectImportExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定を保存しました。アプリを再起動しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_SettingsSavedRestart {
            get {
                return ResourceManager.GetString("Msg_SettingsSavedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API制限中 (Code:{0}) - ポスト取得に失敗する可能性があります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Status_ApiLimited {
            get {
                return ResourceManager.GetString("Msg_Status_ApiLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APIサーバーが不安定です (Code:{0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Status_ApiUnstable {
            get {
                return ResourceManager.GetString("Msg_Status_ApiUnstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続良好 - {0}ms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Status_Connected {
            get {
                return ResourceManager.GetString("Msg_Status_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバーエラー (Code:{0}) - X側で問題発生の可能性 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Status_ServerError {
            get {
                return ResourceManager.GetString("Msg_Status_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新バージョン {0} があります。
        ///
        ///{1}
        ///
        ///更新ページを開きますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_UpdateAvailable {
            get {
                return ResourceManager.GetString("Msg_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} (使用中) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Profile_ActiveSuffix {
            get {
                return ResourceManager.GetString("Profile_ActiveSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイルを選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProfileSelection_NoProfileSelected {
            get {
                return ResourceManager.GetString("ProfileSelection_NoProfileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイルを選択してください: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProfileSelection_Prompt {
            get {
                return ResourceManager.GetString("ProfileSelection_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProfileSelection_Title {
            get {
                return ResourceManager.GetString("ProfileSelection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リスト追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Prompt_AddList {
            get {
                return ResourceManager.GetString("Prompt_AddList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リストID または URL: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Prompt_AddListInput {
            get {
                return ResourceManager.GetString("Prompt_AddListInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル名を入力: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Prompt_NewProfile {
            get {
                return ResourceManager.GetString("Prompt_NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいプロファイル名を入力してください: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Prompt_RenameProfile {
            get {
                return ResourceManager.GetString("Prompt_RenameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Prompt_Search {
            get {
                return ResourceManager.GetString("Prompt_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーワード: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Prompt_SearchKeyword {
            get {
                return ResourceManager.GetString("Prompt_SearchKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイルを選択してください: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Prompt_SelectProfile {
            get {
                return ResourceManager.GetString("Prompt_SelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左端（先頭）に追加する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_AddLeft {
            get {
                return ResourceManager.GetString("Settings_AddLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画クリック時に自動でPiPで開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_AutoPipForVideo {
            get {
                return ResourceManager.GetString("Settings_AutoPipForVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリが非アクティブの時に終了する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_AutoShutdownEnable {
            get {
                return ResourceManager.GetString("Settings_AutoShutdownEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_AutoShutdownMinutes {
            get {
                return ResourceManager.GetString("Settings_AutoShutdownMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動終了 (Auto Shutdown) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_AutoShutdownTitle {
            get {
                return ResourceManager.GetString("Settings_AutoShutdownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   待機時間: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_AutoShutdownWait {
            get {
                return ResourceManager.GetString("Settings_AutoShutdownWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基本動作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_BasicBehavior {
            get {
                return ResourceManager.GetString("Settings_BasicBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェック頻度: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CheckInterval {
            get {
                return ResourceManager.GetString("Settings_CheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時に最新版をチェックする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CheckUpdate {
            get {
                return ResourceManager.GetString("Settings_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラム幅 (px): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ColumnWidth {
            get {
                return ResourceManager.GetString("Settings_ColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのカラムに適用するCSS: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CssLabel {
            get {
                return ResourceManager.GetString("Settings_CssLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メディアクリック時に遷移しない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DisableFocusMedia {
            get {
                return ResourceManager.GetString("Settings_DisableFocusMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポストクリック時に遷移しない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DisableFocusTweet {
            get {
                return ResourceManager.GetString("Settings_DisableFocusTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UI表示オプション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DisplayOptions {
            get {
                return ResourceManager.GetString("Settings_DisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   試験的な機能 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Experimental {
            get {
                return ResourceManager.GetString("Settings_Experimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォーカスモード (単一ビュー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_FocusMode {
            get {
                return ResourceManager.GetString("Settings_FocusMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント設定 (全カラム共通) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Font {
            get {
                return ResourceManager.GetString("Settings_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画の自動再生を強制的に停止する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ForceDisableAutoPlay {
            get {
                return ResourceManager.GetString("Settings_ForceDisableAutoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リストのヘッダーを簡略化する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_HideListHeader {
            get {
                return ResourceManager.GetString("Settings_HideListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホームで左側メニューを非表示にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_HideMenuHome {
            get {
                return ResourceManager.GetString("Settings_HideMenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム以外で左側メニューを非表示にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_HideMenuNonHome {
            get {
                return ResourceManager.GetString("Settings_HideMenuNonHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右側のサイドバー（検索・トレンド）を非表示にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_HideRightSidebar {
            get {
                return ResourceManager.GetString("Settings_HideRightSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未読位置を保持する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_KeepUnread {
            get {
                return ResourceManager.GetString("Settings_KeepUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語 (Language) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Layout {
            get {
                return ResourceManager.GetString("Settings_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Xの自動再生設定(Web)を開く... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Link_AutoplayWeb {
            get {
                return ResourceManager.GetString("Settings_Link_AutoplayWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Xの表示設定(Web)を開く... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Link_DisplayWeb {
            get {
                return ResourceManager.GetString("Settings_Link_DisplayWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リスト自動遷移 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ListAutoNav {
            get {
                return ResourceManager.GetString("Settings_ListAutoNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リスト自動遷移の待機時間 (ms): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ListAutoNavDelay {
            get {
                return ResourceManager.GetString("Settings_ListAutoNavDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※短すぎると正常に遷移できない場合があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ListAutoNavDelayWarning {
            get {
                return ResourceManager.GetString("Settings_ListAutoNavDelayWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規カラムの追加位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NewColumnPos {
            get {
                return ResourceManager.GetString("Settings_NewColumnPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下の単語が含まれるポストを非表示にします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NgWordDesc {
            get {
                return ResourceManager.GetString("Settings_NgWordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録する単語を入力... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NgWordPlaceholder {
            get {
                return ResourceManager.GetString("Settings_NgWordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NGワード設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NgWordTitle {
            get {
                return ResourceManager.GetString("Settings_NgWordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   別プロファイル(アカウント)のタイムライン追加を許可する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_OtherProfileTimeline {
            get {
                return ResourceManager.GetString("Settings_OtherProfileTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PiPウィンドウを常に最前面に表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_PipAlwaysOnTop {
            get {
                return ResourceManager.GetString("Settings_PipAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メディア (Web設定) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Section_MediaWeb {
            get {
                return ResourceManager.GetString("Settings_Section_MediaWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバー状態監視 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ServerMonitor {
            get {
                return ResourceManager.GetString("Settings_ServerMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投稿日時を絶対時刻で表示する (例: 2023/01/01 12:00) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShowAbsoluteTime {
            get {
                return ResourceManager.GetString("Settings_ShowAbsoluteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラム上部にURLを表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ShowColumnUrl {
            get {
                return ResourceManager.GetString("Settings_ShowColumnUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動更新時にページをリロードしない (推奨) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SoftRefresh {
            get {
                return ResourceManager.GetString("Settings_SoftRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   起動時のプロファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_StartupProfile {
            get {
                return ResourceManager.GetString("Settings_StartupProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   前回終了時のプロファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_StartupProfileLastUsed {
            get {
                return ResourceManager.GetString("Settings_StartupProfileLastUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_Behavior {
            get {
                return ResourceManager.GetString("Settings_Tab_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_Column {
            get {
                return ResourceManager.GetString("Settings_Tab_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタムCSS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_CSS {
            get {
                return ResourceManager.GetString("Settings_Tab_CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_Display {
            get {
                return ResourceManager.GetString("Settings_Tab_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ミュート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_Mute {
            get {
                return ResourceManager.GetString("Settings_Tab_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_Others {
            get {
                return ResourceManager.GetString("Settings_Tab_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーマ設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラムを上下2段表示にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_TwoTierLayout {
            get {
                return ResourceManager.GetString("Settings_TwoTierLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ幅に合わせて等分割する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_UniformGrid {
            get {
                return ResourceManager.GetString("Settings_UniformGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最新版の確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_UpdateCheck {
            get {
                return ResourceManager.GetString("Settings_UpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ同士をスナップさせる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_WindowSnap {
            get {
                return ResourceManager.GetString("Settings_WindowSnap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このバージョンをスキップ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SkipVersion {
            get {
                return ResourceManager.GetString("SkipVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status_Checking {
            get {
                return ResourceManager.GetString("Status_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ネットワーク障害の可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status_ConnectionFailed {
            get {
                return ResourceManager.GetString("Status_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続不可 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status_Error {
            get {
                return ResourceManager.GetString("Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status_OK {
            get {
                return ResourceManager.GetString("Status_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不安定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status_Unstable {
            get {
                return ResourceManager.GetString("Status_Unstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日頃よりご利用いただきありがとうございます。
        /// 今後の機能追加やメンテナンス継続のため、 
        ///ご支援をいただけますと大変励みになります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Support_Body {
            get {
                return ResourceManager.GetString("Support_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XColumnの開発を支援する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Support_Header {
            get {
                return ResourceManager.GetString("Support_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご支援・寄付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Support_Title {
            get {
                return ResourceManager.GetString("Support_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモリを解放しました。
        ///上部の 💤 ボタンで再開します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suspend_PausedBody {
            get {
                return ResourceManager.GetString("Suspend_PausedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   💤 休止中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suspend_PausedTitle {
            get {
                return ResourceManager.GetString("Suspend_PausedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエスト制限に到達したため一時停止しました。
        ///しばらく待ってから上部の 💤（休止）ボタンで再開してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suspend_RateLimitBody {
            get {
                return ResourceManager.GetString("Suspend_RateLimitBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ⚠️ API制限 (429) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suspend_RateLimitTitle {
            get {
                return ResourceManager.GetString("Suspend_RateLimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Complete {
            get {
                return ResourceManager.GetString("Title_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Completed {
            get {
                return ResourceManager.GetString("Title_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完全削除の確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_ConfirmDelete {
            get {
                return ResourceManager.GetString("Title_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Created {
            get {
                return ResourceManager.GetString("Title_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除の確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_DeleteConfirm {
            get {
                return ResourceManager.GetString("Title_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイルの複製 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_DuplicateProfile {
            get {
                return ResourceManager.GetString("Title_DuplicateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規プロファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_NewProfile {
            get {
                return ResourceManager.GetString("Title_NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_ProfileSelection {
            get {
                return ResourceManager.GetString("Title_ProfileSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Registered {
            get {
                return ResourceManager.GetString("Title_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前の変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_RenameProfile {
            get {
                return ResourceManager.GetString("Title_RenameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再起動の確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_RestartConfirm {
            get {
                return ResourceManager.GetString("Title_RestartConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_SettingsSaved {
            get {
                return ResourceManager.GetString("Title_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OFFの場合は右端（末尾）に追加されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_AddColumnLeft {
            get {
                return ResourceManager.GetString("Tooltip_AddColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動画を視聴しながらタイムラインを見たい場合に便利です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_AutoPipForVideo {
            get {
                return ResourceManager.GetString("Tooltip_AutoPipForVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動更新のON/OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_AutoRefresh {
            get {
                return ResourceManager.GetString("Tooltip_AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラムをクリアしてメモリを解放します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_ClearColumn {
            get {
                return ResourceManager.GetString("Tooltip_ClearColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空欄にするとサイトのデフォルトに戻ります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_FontFamily {
            get {
                return ResourceManager.GetString("Tooltip_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0=サイト標準 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_FontSize {
            get {
                return ResourceManager.GetString("Tooltip_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザの自動再生ポリシーを厳格化し、ユーザー操作なしでの動画再生を防ぎます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_ForceDisableAutoPlay {
            get {
                return ResourceManager.GetString("Tooltip_ForceDisableAutoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_GoBack {
            get {
                return ResourceManager.GetString("Tooltip_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リプライ(返信)を非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_HideReply {
            get {
                return ResourceManager.GetString("Tooltip_HideReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RT(リポスト)を非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_HideRT {
            get {
                return ResourceManager.GetString("Tooltip_HideRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラムがスクロールされている（トップにいない）場合、自動更新をスキップします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_KeepUnread {
            get {
                return ResourceManager.GetString("Tooltip_KeepUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム読込完了後、リストへ遷移するまでの待ち時間です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_ListAutoNavDelay {
            get {
                return ResourceManager.GetString("Tooltip_ListAutoNavDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サムネイル画像の表示倍率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_MediaScale {
            get {
                return ResourceManager.GetString("ToolTip_MediaScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※メモリ使用量が増える可能性があります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_OtherProfileTimeline {
            get {
                return ResourceManager.GetString("Tooltip_OtherProfileTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_Refresh {
            get {
                return ResourceManager.GetString("Tooltip_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新間隔(秒) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_RefreshInterval {
            get {
                return ResourceManager.GetString("Tooltip_RefreshInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Xサーバーの状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_ServerStatus {
            get {
                return ResourceManager.GetString("Tooltip_ServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [左クリック] Downdetectorで詳細を確認
        ///[右クリック] 今すぐ再チェック
        ///最終確認:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_ServerStatus2 {
            get {
                return ResourceManager.GetString("Tooltip_ServerStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ONの場合、画面内の更新ボタンを自動クリックします。OFFの場合、ページ全体を再読み込みします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_SoftRefresh {
            get {
                return ResourceManager.GetString("Tooltip_SoftRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   休止（メモリ解放） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_Suspend {
            get {
                return ResourceManager.GetString("Tooltip_Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リストを大量に使用する方向けに、カラムを上下に折り返して表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_TwoTierLayout {
            get {
                return ResourceManager.GetString("Tooltip_TwoTierLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ONにすると全てのカラムがウィンドウ内に収まるように自動調整されます（横スクロールなし）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_UniformGrid {
            get {
                return ResourceManager.GetString("Tooltip_UniformGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリ内の動画音量を一括調整します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_Volume {
            get {
                return ResourceManager.GetString("Tooltip_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Auto {
            get {
                return ResourceManager.GetString("UI_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Back {
            get {
                return ResourceManager.GetString("UI_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ← カラム一覧に戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_BackToColumns {
            get {
                return ResourceManager.GetString("UI_BackToColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Refresh {
            get {
                return ResourceManager.GetString("UI_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   待機中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Status_Waiting {
            get {
                return ResourceManager.GetString("UI_Status_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Volume {
            get {
                return ResourceManager.GetString("UI_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新通知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateNotification {
            get {
                return ResourceManager.GetString("UpdateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
    }
}
