//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XColumn.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XColumn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択した項目を削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_DeleteSelected {
            get {
                return ResourceManager.GetString("Common_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」をNGワードに追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ctx_AddNgWord {
            get {
                return ResourceManager.GetString("Ctx_AddNgWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このカラムを削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ctx_DeleteColumn {
            get {
                return ResourceManager.GetString("Ctx_DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_AddHome {
            get {
                return ResourceManager.GetString("Menu_AddHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リスト... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_AddList {
            get {
                return ResourceManager.GetString("Menu_AddList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_AddNotify {
            get {
                return ResourceManager.GetString("Menu_AddNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_AddSearch {
            get {
                return ResourceManager.GetString("Menu_AddSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トレンド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_AddTrend {
            get {
                return ResourceManager.GetString("Menu_AddTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバッグ情報をエクスポート... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_DebugInfo {
            get {
                return ResourceManager.GetString("Menu_DebugInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拡張機能の管理... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Extensions {
            get {
                return ResourceManager.GetString("Menu_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規カラムを追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_NewColumn {
            get {
                return ResourceManager.GetString("Menu_NewColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル(_P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Profile {
            get {
                return ResourceManager.GetString("Menu_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Profile_Delete {
            get {
                return ResourceManager.GetString("Menu_Profile_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複製... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Profile_Duplicate {
            get {
                return ResourceManager.GetString("Menu_Profile_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   別窓で起動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Profile_LaunchNew {
            get {
                return ResourceManager.GetString("Menu_Profile_LaunchNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Profile_Manage {
            get {
                return ResourceManager.GetString("Menu_Profile_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規作成... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Profile_New {
            get {
                return ResourceManager.GetString("Menu_Profile_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前変更... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Profile_Rename {
            get {
                return ResourceManager.GetString("Menu_Profile_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このプロファイルに切り替える に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Profile_Switch {
            get {
                return ResourceManager.GetString("Menu_Profile_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクティブ時自動更新停止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_StopActiveTimer {
            get {
                return ResourceManager.GetString("Menu_StopActiveTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツール(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}
        ///
        ///快適なXライフを。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_About_Body {
            get {
                return ResourceManager.GetString("Msg_About_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在使用中のプロファイル「{0}」を完全に複製するには、アプリの再起動が必要です。
        ///
        ///今すぐ再起動して複製を行いますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ConfirmCloneActiveProfile {
            get {
                return ResourceManager.GetString("Msg_ConfirmCloneActiveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル「{0}」を本当に削除しますか？
        ///設定やカラム情報がすべて失われます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ConfirmDeleteProfile {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイルを「{0}」に切り替えますか？
        ///(アプリが再起動します) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ConfirmProfileSwitch {
            get {
                return ResourceManager.GetString("Msg_ConfirmProfileSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバッグ情報をクリップボードにコピーしました。
        ///サポートに連絡する際に貼り付けてください。
        ///
        ///※この情報には認証トークンなどの機密情報は含まれていませんが、
        ///念のため内容を確認してから送信することをお勧めします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_DebugInfoExported {
            get {
                return ResourceManager.GetString("Msg_DebugInfoExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在使用中のプロファイル「{0}」は削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_CannotDeleteActive {
            get {
                return ResourceManager.GetString("Msg_Err_CannotDeleteActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除中にエラーが発生しました。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_DeleteFailed {
            get {
                return ResourceManager.GetString("Msg_Err_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいウィンドウの起動に失敗しました。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_LaunchFailed {
            get {
                return ResourceManager.GetString("Msg_Err_LaunchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作に失敗しました。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_OperationFailed {
            get {
                return ResourceManager.GetString("Msg_Err_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイルの複製中にエラーが発生しました。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_ProfileCloneFailed {
            get {
                return ResourceManager.GetString("Msg_Err_ProfileCloneFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル「{0}」は既に存在します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_ProfileExists {
            get {
                return ResourceManager.GetString("Msg_Err_ProfileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その名前のプロファイルは既に存在します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_ProfileNameExists {
            get {
                return ResourceManager.GetString("Msg_Err_ProfileNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル名に使用できない文字が含まれています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_ProfileNameInvalid {
            get {
                return ResourceManager.GetString("Msg_Err_ProfileNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前の変更に失敗しました。
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_Err_RenameFailed {
            get {
                return ResourceManager.GetString("Msg_Err_RenameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語設定を変更しました。
        ///変更を完全に適用するにはアプリの再起動が必要です。
        ///
        ///今すぐ再起動しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_LanguageChanged_Restart {
            get {
                return ResourceManager.GetString("Msg_LanguageChanged_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「{0}」をNGワードに追加しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_NgWordAdded {
            get {
                return ResourceManager.GetString("Msg_NgWordAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル「{0}」を作成しました。
        ///新しいプロファイルに切り替えますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ProfileCreated {
            get {
                return ResourceManager.GetString("Msg_ProfileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル「{0}」を削除しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ProfileDeleted {
            get {
                return ResourceManager.GetString("Msg_ProfileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル名を「{0}」に変更しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_ProfileRenamed {
            get {
                return ResourceManager.GetString("Msg_ProfileRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定を変更しました。
        ///反映するにはアプリの再起動が必要です。
        ///今すぐ再起動しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_RestartConfirm {
            get {
                return ResourceManager.GetString("Msg_RestartConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※変更を適用するにはアプリの再起動が必要です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_RestartRequired {
            get {
                return ResourceManager.GetString("Msg_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイル名を入力: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Prompt_NewProfile {
            get {
                return ResourceManager.GetString("Prompt_NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいプロファイル名を入力してください: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Prompt_RenameProfile {
            get {
                return ResourceManager.GetString("Prompt_RenameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左端（先頭）に追加する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_AddLeft {
            get {
                return ResourceManager.GetString("Settings_AddLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基本動作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_BasicBehavior {
            get {
                return ResourceManager.GetString("Settings_BasicBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェック頻度: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CheckInterval {
            get {
                return ResourceManager.GetString("Settings_CheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラム幅 (px): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ColumnWidth {
            get {
                return ResourceManager.GetString("Settings_ColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのカラムに適用するCSS: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_CssLabel {
            get {
                return ResourceManager.GetString("Settings_CssLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メディアクリック時に遷移しない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DisableFocusMedia {
            get {
                return ResourceManager.GetString("Settings_DisableFocusMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポストクリック時に遷移しない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DisableFocusTweet {
            get {
                return ResourceManager.GetString("Settings_DisableFocusTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UI表示オプション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_DisplayOptions {
            get {
                return ResourceManager.GetString("Settings_DisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォーカスモード (単一ビュー) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_FocusMode {
            get {
                return ResourceManager.GetString("Settings_FocusMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォント設定 (全カラム共通) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Font {
            get {
                return ResourceManager.GetString("Settings_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リストのヘッダーを簡略化する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_HideListHeader {
            get {
                return ResourceManager.GetString("Settings_HideListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホームで左側メニューを非表示にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_HideMenuHome {
            get {
                return ResourceManager.GetString("Settings_HideMenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム以外で左側メニューを非表示にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_HideMenuNonHome {
            get {
                return ResourceManager.GetString("Settings_HideMenuNonHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右側のサイドバー（検索・トレンド）を非表示にする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_HideRightSidebar {
            get {
                return ResourceManager.GetString("Settings_HideRightSidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未読位置を保持する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_KeepUnread {
            get {
                return ResourceManager.GetString("Settings_KeepUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語 (Language) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Layout {
            get {
                return ResourceManager.GetString("Settings_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規カラムの追加位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NewColumnPos {
            get {
                return ResourceManager.GetString("Settings_NewColumnPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下の単語が含まれるポストを非表示にします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NgWordDesc {
            get {
                return ResourceManager.GetString("Settings_NgWordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録する単語を入力... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NgWordPlaceholder {
            get {
                return ResourceManager.GetString("Settings_NgWordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NGワード設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_NgWordTitle {
            get {
                return ResourceManager.GetString("Settings_NgWordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバー状態監視 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_ServerMonitor {
            get {
                return ResourceManager.GetString("Settings_ServerMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動更新時にページをリロードしない (推奨) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_SoftRefresh {
            get {
                return ResourceManager.GetString("Settings_SoftRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_Behavior {
            get {
                return ResourceManager.GetString("Settings_Tab_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_Column {
            get {
                return ResourceManager.GetString("Settings_Tab_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタムCSS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_CSS {
            get {
                return ResourceManager.GetString("Settings_Tab_CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_Display {
            get {
                return ResourceManager.GetString("Settings_Tab_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ミュート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Tab_Mute {
            get {
                return ResourceManager.GetString("Settings_Tab_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーマ設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ幅に合わせて等分割する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_UniformGrid {
            get {
                return ResourceManager.GetString("Settings_UniformGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ同士をスナップさせる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings_WindowSnap {
            get {
                return ResourceManager.GetString("Settings_WindowSnap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status_Checking {
            get {
                return ResourceManager.GetString("Status_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続不可 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status_Error {
            get {
                return ResourceManager.GetString("Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status_OK {
            get {
                return ResourceManager.GetString("Status_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不安定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status_Unstable {
            get {
                return ResourceManager.GetString("Status_Unstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_About {
            get {
                return ResourceManager.GetString("Title_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Complete {
            get {
                return ResourceManager.GetString("Title_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完全削除の確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_ConfirmDelete {
            get {
                return ResourceManager.GetString("Title_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Created {
            get {
                return ResourceManager.GetString("Title_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロファイルの複製 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_DuplicateProfile {
            get {
                return ResourceManager.GetString("Title_DuplicateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規プロファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_NewProfile {
            get {
                return ResourceManager.GetString("Title_NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Registered {
            get {
                return ResourceManager.GetString("Title_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前の変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_RenameProfile {
            get {
                return ResourceManager.GetString("Title_RenameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再起動の確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_RestartConfirm {
            get {
                return ResourceManager.GetString("Title_RestartConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OFFの場合は右端（末尾）に追加されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_AddColumnLeft {
            get {
                return ResourceManager.GetString("Tooltip_AddColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動更新のON/OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_AutoRefresh {
            get {
                return ResourceManager.GetString("Tooltip_AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空欄にするとサイトのデフォルトに戻ります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_FontFamily {
            get {
                return ResourceManager.GetString("Tooltip_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0=サイト標準 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_FontSize {
            get {
                return ResourceManager.GetString("Tooltip_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_GoBack {
            get {
                return ResourceManager.GetString("Tooltip_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リプライ(返信)を非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_HideReply {
            get {
                return ResourceManager.GetString("Tooltip_HideReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RT(リポスト)を非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_HideRT {
            get {
                return ResourceManager.GetString("Tooltip_HideRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラムがスクロールされている（トップにいない）場合、自動更新をスキップします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_KeepUnread {
            get {
                return ResourceManager.GetString("Tooltip_KeepUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_Refresh {
            get {
                return ResourceManager.GetString("Tooltip_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新間隔(秒) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_RefreshInterval {
            get {
                return ResourceManager.GetString("Tooltip_RefreshInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Xサーバーの状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_ServerStatus {
            get {
                return ResourceManager.GetString("Tooltip_ServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [左クリック] Downdetectorで詳細を確認
        ///[右クリック] 今すぐ再チェック
        ///最終確認:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_ServerStatus2 {
            get {
                return ResourceManager.GetString("Tooltip_ServerStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ONの場合、画面内の更新ボタンを自動クリックします。OFFの場合、ページ全体を再読み込みします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_SoftRefresh {
            get {
                return ResourceManager.GetString("Tooltip_SoftRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ONにすると全てのカラムがウィンドウ内に収まるように自動調整されます（横スクロールなし）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_UniformGrid {
            get {
                return ResourceManager.GetString("Tooltip_UniformGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリ内の動画音量を一括調整します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tooltip_Volume {
            get {
                return ResourceManager.GetString("Tooltip_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Auto {
            get {
                return ResourceManager.GetString("UI_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Back {
            get {
                return ResourceManager.GetString("UI_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ← カラム一覧に戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_BackToColumns {
            get {
                return ResourceManager.GetString("UI_BackToColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Refresh {
            get {
                return ResourceManager.GetString("UI_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   待機中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Status_Waiting {
            get {
                return ResourceManager.GetString("UI_Status_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Volume {
            get {
                return ResourceManager.GetString("UI_Volume", resourceCulture);
            }
        }
    }
}
